twig:
    default_path: '%kernel.project_dir%/templates'
        #globals:
        #    app_name: 'Phénix'

    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
